on:
  pull_request:
    paths-ignore:
      - 'CHANGELOG.md'
      - 'CHANGELOG_PENDING.md'
  push:
    branches:
      - *
    tags:
      - v*.*.*
    paths-ignore:
      - 'CHANGELOG.md'
      - 'CHANGELOG_PENDING.md'

env:
  PULUMI_API: https://api.pulumi-staging.io
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  AWS_REGION: us-west-2
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup dotnet SDK v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Build Pulumi SDK
        run: dotnet run build-sdk
      - name: Test Pulumi SDK
        run: dotnet run test-sdk
      - name: Test Pulumi Automation SDK
        run: dotnet run test-automation-sdk
      - name: Set up Go 1.19.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: Integration Tests
        run: dotnet run integration-tests